// Common
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Newsletter
export const SAVE_NEWSLETTER_SUCCESS = 'SAVE_NEWSLETTER_SUCCESS';
export const SAVE_NEWSLETTER_ERROR = 'SAVE_NEWSLETTER_ERROR';

// Home Page
export const HOME_SEARCH_REQUEST = "HOME_SEARCH_REQUEST";
export const LOAD_SEARCH_SUCCESS = "LOAD_SEARCH_SUCCESS";
export const CLEAR_SEARCHES = "CLEAR_SEARCHES";
export const SEARCH_ERROR = "SEARCH_ERROR";

// Feature
export const LOAD_HEADER_SUCCESS = "LOAD_HEADER_SUCCESS";
export const LOAD_LAST_MINUTE_FEATURE_SUCCESS = "LOAD_LAST_MINUTE_FEATURE_SUCCESS";

// Deals
export const LOAD_HOT_DEAL_SUCCESS = "LOAD_HOT_DEAL_SUCCESS";
export const LOAD_SPECIAL_DEAL_SUCCESS = "LOAD_SPECIAL_DEAL_SUCCESS";
export const LOAD_TRENDING_DEAL_SUCCESS = "LOAD_TRENDING_DEAL_SUCCESS";

export const LOAD_HOTEL_DEAL_SUCCESS = "LOAD_HOTEL_DEAL_SUCCESS";
export const LOAD_RESTAURANT_DEAL_SUCCESS = "LOAD_RESTAURANT_DEAL_SUCCESS";
export const LOAD_ATTRACTION_DEAL_SUCCESS = "LOAD_ATTRACTION_DEAL_SUCCESS";

// Questions
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_GENERIC_QUESTIONS_SUCCESS = 'LOAD_GENERIC_QUESTIONS_SUCCESS';

// Comments
export const LOAD_REVIEWS_SUCCESS = 'LOAD_REVIEWS_SUCCESS';

//Post Review
export const REVIEW_REQUEST = 'REVIEW_REQUEST';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';
export const CLEAR_REVIEW = 'CLEAR_REVIEW';

// Locations
export const LOAD_AREA_SUCCESS = 'LOAD_AREA_SUCCESS';

// Place
export const LOAD_PLACES_SUCCESS = 'LOAD_PLACES_SUCCESS';
export const LOAD_TOP_PLACE_SUCCESS = 'LOAD_TOP_PLACE_SUCCESS';
export const LOAD_PLACE_SUCCESS = 'LOAD_PLACE_SUCCESS';

// Hotels
export const SEARCH_HOTEL_SUCCESS = 'SEARCH_HOTEL_SUCCESS';

export const SAVE_CURRENCY_SUCCESS = 'SAVE_CURRENCY_SUCCESS';

// Authentication

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const PASSWORD_REQUEST = 'PASSWORD_REQUEST';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_FAILURE = 'PASSWORD_FAILURE';

export const LOAD_TOP_DESTINATIONS_SUCCESS = 'LOAD_TOP_DESTINATIONS_SUCCESS';