// Authentication
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const PASSWORD_REQUEST = 'PASSWORD_REQUEST';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_FAILURE = 'PASSWORD_FAILURE';

// Autocomplete
export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_FAILURE = 'AUTOCOMPLETE_FAILURE';
export const AUTOCOMPLETE_CLEAR = 'AUTOCOMPLETE_CLEAR';

// Content Actions
export const HEADER_CONTENT_REQUEST = 'HEADER_CONTENT_REQUEST';
export const HEADER_CONTENT_SUCCESS = 'HEADER_CONTENT_SUCCESS';
export const HEADER_CONTENT_FAILURE = 'HEADER_CONTENT_FAILURE';

// Events
export const EVENT_CONTENT_REQUEST = 'EVENT_CONTENT_REQUEST';
export const EVENT_CONTENT_SUCCESS = 'EVENT_CONTENT_SUCCESS';
export const EVENT_CONTENT_FAILURE = 'EVENT_CONTENT_FAILURE';

export const EVENT_CATEGORY_REQUEST = 'EVENT_CATEGORY_REQUEST';
export const EVENT_CATEGORY_SUCCESS = 'EVENT_CATEGORY_SUCCESS';
export const EVENT_CATEGORY_FAILURE = 'EVENT_CATEGORY_FAILURE';

export const EVENTS_BY_CATEGORY_REQUEST = 'EVENTS_BY_CATEGORY_REQUEST';
export const EVENTS_BY_CATEGORY_SUCCESS = 'EVENTS_BY_CATEGORY_SUCCESS';
export const EVENTS_BY_CATEGORY_FAILURE = 'EVENTS_BY_CATEGORY_FAILURE';

// Location
export const LOCATION_CONTENT_REQUEST = 'LOCATION_CONTENT_REQUEST';
export const LOCATION_CONTENT_SUCCESS = 'LOCATION_CONTENT_SUCCESS';
export const LOCATION_CONTENT_FAILURE = 'LOCATION_CONTENT_FAILURE';

// Attractions
export const ATTRACTION_CONTENT_REQUEST = 'ATTRACTION_CONTENT_REQUEST';
export const ATTRACTION_CONTENT_SUCCESS = 'ATTRACTION_CONTENT_SUCCESS';
export const ATTRACTION_CONTENT_FAILURE = 'ATTRACTION_CONTENT_FAILURE';

export const ATTRACTION_CATEGORY_REQUEST = 'ATTRACTION_CATEGORY_REQUEST';
export const ATTRACTION_CATEGORY_SUCCESS = 'ATTRACTION_CATEGORY_SUCCESS';
export const ATTRACTION_CATEGORY_FAILURE = 'ATTRACTION_CATEGORY_FAILURE';

// Child Locations
export const CHILD_LOCATION_CONTENT_REQUEST = 'CHILD_LOCATION_CONTENT_REQUEST';
export const CHILD_LOCATION_CONTENT_SUCCESS = 'CHILD_LOCATION_CONTENT_SUCCESS';
export const CHILD_LOCATION_CONTENT_FAILURE = 'CHILD_LOCATION_CONTENT_FAILURE';

// Hotel Deals
export const HOTEL_DEALS_REQUEST = 'HOTEL_DEALS_REQUEST';
export const HOTEL_DEALS_SUCCESS = 'HOTEL_DEALS_SUCCESS';
export const HOTEL_DEALS_FAILURE = 'HOTEL_DEALS_FAILURE';

// Newsletter
export const NEWSLETTER_REQUEST = 'NEWSLETTER_REQUEST';
export const NEWSLETTER_SUCCESS = 'NEWSLETTER_SUCCESS';
export const NEWSLETTER_FAILURE = 'NEWSLETTER_FAILURE';

//Post Question
export const POST_QUESTION_REQUEST = 'QUESTION_REQUEST';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_FAILURE = 'POST_QUESTION_FAILURE';

// Questions
export const LOAD_QUESTIONS_REQUEST = 'LOAD_QUESTIONS_REQUEST';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILURE = 'LOAD_QUESTIONS_FAILURE';

// Open Review Model
export const OPEN_REVIEW_MODEL = 'OPEN_REVIEW_MODEL';

// Post Review
export const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST';
export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';

// Load Reviews
export const LOAD_REVIEWS_REQUEST = 'LOAD_REVIEWS_REQUEST';
export const LOAD_REVIEWS_SUCCESS = 'LOAD_REVIEWS_SUCCESS';
export const LOAD_REVIEWS_FAILURE = 'LOAD_REVIEWS_FAILURE';

// Destinations
export const DESTINATIONS_REQUEST = 'DESTINATIONS_REQUEST';
export const DESTINATIONS_SUCCESS = 'DESTINATIONS_SUCCESS';
export const DESTINATIONS_FAILURE = 'DESTINATIONS_FAILURE';

// Like Reviews
export const LIKE_REVIEW_REQUEST = 'LIKE_REVIEW_REQUEST';
export const LIKE_REVIEW_SUCCESS = 'LIKE_REVIEW_SUCCESS';
export const LIKE_REVIEW_FAILURE = 'LIKE_REVIEW_FAILURE';

// Flights
export const SEARCH_FLIGHTS_REQUEST = 'SEARCH_FLIGHTS_REQUEST';
export const SEARCH_FLIGHTS_SUCCESS = 'SEARCH_FLIGHTS_SUCCESS';
export const SEARCH_FLIGHTS_FAILURE = 'SEARCH_FLIGHTS_FAILURE';

//Airport
export const AIRPORT_REQUEST = 'AIRPORT_REQUEST';
export const AIRPORT_SUCCESS = 'AIRPORT_SUCCESS';
export const AIRPORT_FAILURE = 'AIRPORT_FAILURE';

// Common
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


// Home Page
export const HOME_SEARCH_REQUEST = "HOME_SEARCH_REQUEST";
export const LOAD_SEARCH_SUCCESS = "LOAD_SEARCH_SUCCESS";
export const CLEAR_SEARCHES = "CLEAR_SEARCHES";
export const SEARCH_ERROR = "SEARCH_ERROR";

// Weather
export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_FAILURE = 'WEATHER_FAILURE';

// Airport Parking
export const AIRPORT_PARKING_REQUEST = 'AIRPORT_PARKING_REQUEST';
export const AIRPORT_PARKING_SUCCESS = 'AIRPORT_PARKING_SUCCESS';
export const AIRPORT_PARKING_FAILURE = 'AIRPORT_PARKING_FAILURE';

// Airport Hotel
export const AIRPORT_HOTEL_REQUEST = 'AIRPORT_HOTEL_REQUEST';
export const AIRPORT_HOTEL_SUCCESS = 'AIRPORT_HOTEL_SUCCESS';
export const AIRPORT_HOTEL_FAILURE = 'AIRPORT_HOTEL_FAILURE';

// Airport Lounge
export const AIRPORT_LOUNGE_REQUEST = 'AIRPORT_LOUNGE_REQUEST';
export const AIRPORT_LOUNGE_SUCCESS = 'AIRPORT_LOUNGE_SUCCESS';
export const AIRPORT_LOUNGE_FAILURE = 'AIRPORT_LOUNGE_FAILURE';

// Restaurant
export const RESTAURANT_CATEGORY_REQUEST = 'RESTAURANT_CATEGORY_REQUEST';
export const RESTAURANT_CATEGORY_SUCCESS = 'RESTAURANT_CATEGORY_SUCCESS';
export const RESTAURANT_CATEGORY_FAILURE = 'RESTAURANT_CATEGORY_FAILURE';

export const RESTAURANT_CONTENT_REQUEST = 'RESTAURANT_CONTENT_REQUEST';
export const RESTAURANT_CONTENT_SUCCESS = 'RESTAURANT_CONTENT_SUCCESS';
export const RESTAURANT_CONTENT_FAILURE = 'RESTAURANT_CONTENT_FAILURE';

// Nightlife
export const NIGHTLIFE_CATEGORY_REQUEST = 'NIGHTLIFE_CATEGORY_REQUEST';
export const NIGHTLIFE_CATEGORY_SUCCESS = 'NIGHTLIFE_CATEGORY_SUCCESS';
export const NIGHTLIFE_CATEGORY_FAILURE = 'NIGHTLIFE_CATEGORY_FAILURE';

export const NIGHTLIFE_CONTENT_REQUEST = 'NIGHTLIFE_CONTENT_REQUEST';
export const NIGHTLIFE_CONTENT_SUCCESS = 'NIGHTLIFE_CONTENT_SUCCESS';
export const NIGHTLIFE_CONTENT_FAILURE = 'NIGHTLIFE_CONTENT_FAILURE';






export const LOAD_LAST_MINUTE_FEATURE_SUCCESS = "LOAD_LAST_MINUTE_FEATURE_SUCCESS";

// Deals
export const LOAD_HOT_DEAL_SUCCESS = "LOAD_HOT_DEAL_SUCCESS";
export const LOAD_SPECIAL_DEAL_SUCCESS = "LOAD_SPECIAL_DEAL_SUCCESS";
export const LOAD_TRENDING_DEAL_SUCCESS = "LOAD_TRENDING_DEAL_SUCCESS";

export const LOAD_HOTEL_DEAL_SUCCESS = "LOAD_HOTEL_DEAL_SUCCESS";
export const LOAD_RESTAURANT_DEAL_SUCCESS = "LOAD_RESTAURANT_DEAL_SUCCESS";
export const LOAD_ATTRACTION_DEAL_SUCCESS = "LOAD_ATTRACTION_DEAL_SUCCESS";

export const LOAD_GENERIC_QUESTIONS_SUCCESS = 'LOAD_GENERIC_QUESTIONS_SUCCESS';

//Post Review
export const CLEAR_REVIEW = 'CLEAR_REVIEW';

export const CLEAR_QUESTION = 'CLEAR_QUESTION';

// Locations
export const LOAD_LOCATION_SUCCESS = 'LOAD_LOCATION_SUCCESS';
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const LOAD_LOCATIONS_REQUEST = 'LOAD_LOCATIONS_REQUEST';

// Place
export const LOAD_PLACES_SUCCESS = 'LOAD_PLACES_SUCCESS';
export const LOAD_TOP_PLACE_SUCCESS = 'LOAD_TOP_PLACE_SUCCESS';
export const LOAD_PLACE_SUCCESS = 'LOAD_PLACE_SUCCESS';

// Hotels
export const SEARCH_HOTEL_SUCCESS = 'SEARCH_HOTEL_SUCCESS';

export const SAVE_CURRENCY_SUCCESS = 'SAVE_CURRENCY_SUCCESS';




