// Common
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Newsletter
export const LOAD_NEWSLETTER_SUCCESS = 'LOAD_NEWSLETTER_SUCCESS';

// Home Page
export const HOME_SEARCH_REQUEST = "HOME_SEARCH_REQUEST";
export const LOAD_SEARCH_SUCCESS = "LOAD_SEARCH_SUCCESS";
export const CLEAR_SEARCHES = "CLEAR_SEARCHES";

// Feature
export const LOAD_FEATURE_SUCCESS = "LOAD_FEATURE_SUCCESS";
export const LOAD_LAST_MINUTE_FEATURE_SUCCESS = "LOAD_LAST_MINUTE_FEATURE_SUCCESS";

// Deals
export const LOAD_HOT_DEAL_SUCCESS = "LOAD_HOT_DEAL_SUCCESS";
export const LOAD_SPECIAL_DEAL_SUCCESS = "LOAD_SPECIAL_DEAL_SUCCESS";
export const LOAD_TRENDING_DEAL_SUCCESS = "LOAD_TRENDING_DEAL_SUCCESS";

export const LOAD_HOTEL_DEAL_SUCCESS = "LOAD_HOTEL_DEAL_SUCCESS";
export const LOAD_RESTAURANT_DEAL_SUCCESS = "LOAD_RESTAURANT_DEAL_SUCCESS";
export const LOAD_ATTRACTION_DEAL_SUCCESS = "LOAD_ATTRACTION_DEAL_SUCCESS";

// Questions
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_GENERIC_QUESTIONS_SUCCESS = 'LOAD_GENERIC_QUESTIONS_SUCCESS';

// Comments
export const LOAD_REVIEWS_SUCCESS = 'LOAD_REVIEWS_SUCCESS';
export const LOAD_GENERIC_REVIEWS_SUCCESS = 'LOAD_GENERIC_REVIEWS_SUCCESS';

// Locations
export const LOAD_AREA_SUCCESS = 'LOAD_AREA_SUCCESS';

// Place
export const LOAD_PLACES_SUCCESS = 'LOAD_PLACES_SUCCESS';
export const LOAD_TOP_PLACE_SUCCESS = 'LOAD_TOP_PLACE_SUCCESS';
export const LOAD_PLACE_SUCCESS = 'LOAD_PLACE_SUCCESS';

// Hotels
export const SEARCH_HOTEL_SUCCESS = 'SEARCH_HOTEL_SUCCESS';

export const SAVE_CURRENCY_SUCCESS = 'SAVE_CURRENCY_SUCCESS';